# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "ec2_node_exporters"
    scrape_interval: 15s
    consul_sd_configs:
      - server: "localhost:8500"
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__address__"
        regex: "(.*):(.*)"
        replacement: "$1:9100"
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
      - source_labels: ["__meta_consul_node"]
        regex: "k8s-sync"
        action: drop

  - job_name: "eks_node_exporters"
    scrape_interval: 15s
    consul_sd_configs:
      - server: "localhost:8500"
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__address__"
        regex: "(.*):(.*)"
        replacement: "$1:9100"
      - source_labels: ["__meta_consul_service_address"]
        target_label: "instance"
      - source_labels: ["__meta_consul_node"]
        regex: "k8s-sync"
        action: keep
      - source_labels: ["__meta_consul_service"]
        regex: "node-exporter-(.*)"
        action: keep

  - job_name: "consul_metrics"
    scrape_interval: 15s
    consul_sd_configs:
      - server: "localhost:8500"
        services:
          - consul
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__address__"
        regex: "(.*):(.*)"
        replacement: "$1:8500"
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
    metrics_path: "/v1/agent/metrics"
    params:
      format: ["prometheus"]

  - job_name: "federated cluster"
    scrape_interval: 15s
    consul_sd_configs:
      - server: "localhost:8500"
        services:
          - prometheus-service-monitoring
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__address__"
        regex: "(.*):(.*)"
        replacement: "$1:9090"
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
    honor_labels: true
    metrics_path: "/federate"
    params:
      "match[]":
        - '{job="kandula-metrics"}'
        - '{__name__=~"kube.*"}'
