---
- name: create monitoring manifests directory
  file:
    path: /home/ubuntu/monitoring_manifests
    state: directory
  tags:
    - deploy_monitoring_eks

- name: copy monitoring manifest files
  copy:
    src: ./files/kuberenetes-manifests
    dest: /home/ubuntu/monitoring_manifests
  tags:
    - deploy_monitoring_eks

- name: deploy prometheus and kube-state-metrics
  shell: kubectl apply -f /home/ubuntu/monitoring_manifests
  tags:
    - deploy_monitoring_eks
