---
- name: opsschool final-project playbook
  # hosts: service_instance_true
  hosts:
    - service_instance_true
    - bastion_host_true
    - bootstrap_server_true
  gather_facts: yes

  tasks:
    - name: include bootstrap role
      vars:
        ansible_become: yes
      include_role:
        name: bootstrap
      when: inventory_hostname in groups.bootstrap_server_true
      tags:
        - include_bootstrap_role
        - install_kubectl
        - install_helm

    - name: include psql role
      vars:
        ansible_become: yes
      include_role:
        name: psql
      when: inventory_hostname in groups.bootstrap_server_true
      tags:
        - include_psql_role

    - name: include consul role
      vars:
        ansible_become: yes
      include_role:
        name: consul
      when: inventory_hostname in lookup('inventory_hostnames', 'service_instance_true:bootstrap_server_true:bastion_host_true')
      tags:
        - include_consul_role
        - install_consul_services
        - install_consul_eks
        - configure_consul

    - name: include jenkins_server role
      vars:
        ansible_become: yes
      include_role:
        name: jenkins-server
      when: inventory_hostname in groups.jenkins_server_true
      tags:
        - include_jenkins_role

    - name: include jenkins_agents role
      vars:
        ansible_become: yes
      include_role:
        name: jenkins-agents
      when: inventory_hostname in groups.jenkins_agent_true
      tags:
        - include_jenkins_agent_role

    - name: include prometheus role
      vars:
        ansible_become: yes
      include_role:
        name: prometheus
      when: inventory_hostname in lookup('inventory_hostnames', 'monitoring_true:bootstrap_server_true')
      tags:
        - include_prometheus_role
        - install_grafana
        - configure_prometheus
        - configure_grafana

    - name: include node_exporter role
      vars:
        ansible_become: yes
      include_role:
        name: install_node_exporter
      when: inventory_hostname in lookup('inventory_hostnames', 'service_instance_true:bootstrap_server_true:bastion_host_true')
      tags:
        - include_node_exporter_role

    - name: include elk role
      vars:
        ansible_become: yes
      include_role:
        name: elk
      when: inventory_hostname in groups.elk_server_true
      tags:
        - include_elk_role
        - configure_kibana

    - name: include filebeat role
      vars:
        ansible_become: yes
      include_role:
        name: filebeat
      when: inventory_hostname in lookup('inventory_hostnames', 'service_instance_true:bootstrap_server_true:bastion_host_true')
      tags:
        - include_filebeat_role
        - configure_filebeat
