---
- name: opsschool final-project playbook
  # hosts: service_instance_true
  hosts: 
    - service_instance_true
    - bastion_host_true 
  gather_facts: yes

  tasks:
    - name: include consul role
      vars:
        ansible_become: yes
      include_role:
        name: consul
      when: inventory_hostname in groups.service_instance_true
      tags:
        - include_consul_role

    - name: include psql role
      vars:
        ansible_become: yes
      include_role:
        name: psql
      when: inventory_hostname in groups.bastion_host_true
      tags:
        - include_psql_role
  
    - name: include jenkins_server role
      vars:
        ansible_become: yes
      include_role: 
        name: jenkins-server
      when: inventory_hostname in groups.jenkins_server_true
      tags: 
        - include_jenkins_role

    - name: include jenkins_agents role
      vars:
        ansible_become: yes
      include_role: 
        name: jenkins-agents
      when: inventory_hostname in groups.jenkins_agent_true
      tags: 
        - include_jenkins_agent_role

    - name: include prometheus role
      vars:
        ansible_become: yes
      include_role:
        name: prometheus
      when: inventory_hostname in groups.monitoring_true
      tags:
        - include_prometheus_role
        - install_grafana

    - name: include node_exporter role
      vars:
        ansible_become: yes
      include_role:
        name: install_node_exporter
      when: inventory_hostname in groups.service_instance_true
      tags:
        - include_node_exporter_role